import { JAPANESE_FOUNDATION_TRANSLATIONS } from '../../japaneseFoundationTranslations.generated.js';
import { normalizeJapaneseFoundationLanguage } from '../../utils/japaneseFoundationLanguages.js';

export const KANA_ROWS = [
    { label: '∅', cells: [['あ', 'ア', 'a'], ['い', 'イ', 'i'], ['う', 'ウ', 'u'], ['え', 'エ', 'e'], ['お', 'オ', 'o']] },
    { label: 'K', cells: [['か', 'カ', 'ka'], ['き', 'キ', 'ki'], ['く', 'ク', 'ku'], ['け', 'ケ', 'ke'], ['こ', 'コ', 'ko']] },
    { label: 'S', cells: [['さ', 'サ', 'sa'], ['し', 'シ', 'shi'], ['す', 'ス', 'su'], ['せ', 'セ', 'se'], ['そ', 'ソ', 'so']] },
    { label: 'T', cells: [['た', 'タ', 'ta'], ['ち', 'チ', 'chi'], ['つ', 'ツ', 'tsu'], ['て', 'テ', 'te'], ['と', 'ト', 'to']] },
    { label: 'N', cells: [['な', 'ナ', 'na'], ['に', 'ニ', 'ni'], ['ぬ', 'ヌ', 'nu'], ['ね', 'ネ', 'ne'], ['の', 'ノ', 'no']] },
    { label: 'H', cells: [['は', 'ハ', 'ha'], ['ひ', 'ヒ', 'hi'], ['ふ', 'フ', 'fu'], ['へ', 'ヘ', 'he'], ['ほ', 'ホ', 'ho']] },
    { label: 'M', cells: [['ま', 'マ', 'ma'], ['み', 'ミ', 'mi'], ['む', 'ム', 'mu'], ['め', 'メ', 'me'], ['も', 'モ', 'mo']] },
    { label: 'Y', cells: [['や', 'ヤ', 'ya'], null, ['ゆ', 'ユ', 'yu'], null, ['よ', 'ヨ', 'yo']] },
    { label: 'R', cells: [['ら', 'ラ', 'ra'], ['り', 'リ', 'ri'], ['る', 'ル', 'ru'], ['れ', 'レ', 're'], ['ろ', 'ロ', 'ro']] },
    { label: 'W', cells: [['わ', 'ワ', 'wa'], null, null, null, ['を', 'ヲ', 'wo']] },
    { label: 'N', cells: [['ん', 'ン', 'n'], null, null, null, null] },
];

export const VOICED_KANA = [
    { label: '浊音 G', labelEn: 'Voiced G', pairs: [['か', 'が', 'ga'], ['き', 'ぎ', 'gi'], ['く', 'ぐ', 'gu'], ['け', 'げ', 'ge'], ['こ', 'ご', 'go']] },
    { label: '浊音 Z', labelEn: 'Voiced Z', pairs: [['さ', 'ざ', 'za'], ['し', 'じ', 'ji'], ['す', 'ず', 'zu'], ['せ', 'ぜ', 'ze'], ['そ', 'ぞ', 'zo']] },
    { label: '浊音 D', labelEn: 'Voiced D', pairs: [['た', 'だ', 'da'], ['ち', 'ぢ', 'ji'], ['つ', 'づ', 'zu'], ['て', 'で', 'de'], ['と', 'ど', 'do']] },
    { label: '浊音 B', labelEn: 'Voiced B', pairs: [['は', 'ば', 'ba'], ['ひ', 'び', 'bi'], ['ふ', 'ぶ', 'bu'], ['へ', 'べ', 'be'], ['ほ', 'ぼ', 'bo']] },
    { label: '半浊音 P', labelEn: 'Semi-voiced P', pairs: [['は', 'ぱ', 'pa'], ['ひ', 'ぴ', 'pi'], ['ふ', 'ぷ', 'pu'], ['へ', 'ぺ', 'pe'], ['ほ', 'ぽ', 'po']] },
];

export const CONTRACTED_SOUNDS = [
    ['きゃ', 'キャ', 'kya'], ['きゅ', 'キュ', 'kyu'], ['きょ', 'キョ', 'kyo'],
    ['しゃ', 'シャ', 'sha'], ['しゅ', 'シュ', 'shu'], ['しょ', 'ショ', 'sho'],
    ['ちゃ', 'チャ', 'cha'], ['ちゅ', 'チュ', 'chu'], ['ちょ', 'チョ', 'cho'],
    ['にゃ', 'ニャ', 'nya'], ['にゅ', 'ニュ', 'nyu'], ['にょ', 'ニョ', 'nyo'],
    ['ひゃ', 'ヒャ', 'hya'], ['ひゅ', 'ヒュ', 'hyu'], ['ひょ', 'ヒョ', 'hyo'],
    ['みゃ', 'ミャ', 'mya'], ['みゅ', 'ミュ', 'myu'], ['みょ', 'ミョ', 'myo'],
    ['りゃ', 'リャ', 'rya'], ['りゅ', 'リュ', 'ryu'], ['りょ', 'リョ', 'ryo'],
    ['ぎゃ', 'ギャ', 'gya'], ['じゃ', 'ジャ', 'ja'], ['びょ', 'ビョ', 'byo'], ['ぴゅ', 'ピュ', 'pyu'],
];

export const KANA_QUIZ = [
    { kana: 'あ', answer: 'a', choices: ['a', 'o', 'me', 'nu'] },
    { kana: 'き', answer: 'ki', choices: ['ki', 'sa', 'chi', 'ri'] },
    { kana: 'ぬ', answer: 'nu', choices: ['me', 'nu', 'ne', 'no'] },
    { kana: 'れ', answer: 're', choices: ['wa', 'ne', 're', 'ru'] },
    { kana: 'シ', answer: 'shi', choices: ['shi', 'tsu', 'so', 'n'] },
    { kana: 'ツ', answer: 'tsu', choices: ['shi', 'tsu', 'chi', 'su'] },
    { kana: 'フ', answer: 'fu', choices: ['wa', 'u', 'fu', 'ra'] },
    { kana: 'ヨ', answer: 'yo', choices: ['yo', 'ko', 'ro', 'ma'] },
    { kana: 'ぎ', answer: 'gi', choices: ['ki', 'gi', 'ji', 'ri'] },
    { kana: 'ぴょ', answer: 'pyo', choices: ['hyo', 'pyo', 'pyu', 'byo'] },
    { kana: 'しゃ', answer: 'sha', choices: ['sha', 'shiya', 'sa', 'ja'] },
    { kana: 'ん', answer: 'n', choices: ['n', 'so', 'shi', 'ri'] },
];

export const MORA_QUIZ = [
    { text: 'にほん', reading: 'に・ほ・ん', answer: 3 },
    { text: 'きって', reading: 'き・っ・て', answer: 3 },
    { text: 'りょこう', reading: 'りょ・こ・う', answer: 3 },
    { text: 'がくせい', reading: 'が・く・せ・い', answer: 4 },
    { text: 'とうきょう', reading: 'と・う・きょ・う', answer: 4 },
    { text: 'しんぶん', reading: 'し・ん・ぶ・ん', answer: 4 },
];

export const KANJI_QUIZ = [
    { word: '日本', answer: 'にほん', choices: ['にほん', 'にちほん', 'ひもと', 'じつほん'] },
    { word: '学生', answer: 'がくせい', choices: ['がくせい', 'がくしょう', 'まなびせい', 'がっせい'] },
    { word: '食べる', answer: 'たべる', choices: ['しょくべる', 'たべる', 'くべる', 'たべり'] },
    { word: '大人', answer: 'おとな', choices: ['だいじん', 'おとな', 'たいにん', 'おおひと'] },
    { word: '今日', answer: 'きょう', choices: ['こんにち', 'きょう', 'いまひ', 'こんじつ'] },
];

export const TYPING_PRACTICE = [
    { target: 'こんにちは', romaji: 'konnichiha', accepted: ['こんにちは'] },
    { target: 'きって', romaji: 'kitte', accepted: ['きって'] },
    { target: 'りょこう', romaji: 'ryokou', accepted: ['りょこう', '旅行'] },
    { target: '日本語', romaji: 'nihongo → Space → Enter', accepted: ['日本語', 'にほんご'] },
    { target: '今日は日本語を勉強します。', romaji: 'kyouha nihongo wo benkyoushimasu.', accepted: ['今日は日本語を勉強します。', '今日は日本語を勉強します'] },
];

export const FOUNDATION_COPY = {
    zh: {
        common: {
            courseBadge: 'Chilan · 日语入门基础',
            back: '返回',
            step: '步骤',
            listen: '听发音',
            listening: '正在播放',
            audioError: '暂时无法播放，请检查网络或稍后再试。',
            readingOnly: '先理解规律，不要求一次背完',
            quiz: '小测验',
            correct: '正确',
            incorrect: '再想一想',
            next: '下一题',
            restart: '重新开始',
            score: '得分 {{score}} / {{total}}',
        },
        intro: {
            eyebrow: '开始之前',
            slidesAriaLabel: '日语课程导览幻灯片',
            title: '先看懂日语这套系统，再开始背句子',
            subtitle: '日语的难点不是某一个规则，而是三套文字、声音节拍、词形变化和语境同时工作。本导览告诉你每个模块学什么、什么时候够用。',
            scriptTitle: '三套文字，各有分工',
            scripts: [
                { glyph: 'あ', title: '平假名', tag: '语法与日语固有词', body: '助词、词尾和许多常用词都用平假名。先做到看到就能读，不依赖罗马字。', example: 'わたしは学生です。' },
                { glyph: 'ア', title: '片假名', tag: '外来语与强调', body: '外来语、人名、拟声词常用片假名。它与平假名表示同一套基本音。', example: 'コーヒーを飲みます。' },
                { glyph: '漢', title: '汉字', tag: '词义与词干', body: '汉字压缩信息，但读音随词而变。学习单位应是“词＋读音＋语境”，不是孤立汉字。', example: '日本語を勉強します。' },
            ],
            principlesTitle: '这门课怎么学',
            principles: [
                { title: '先听再看', body: '先听完整表达，再借助假名和翻译核对；培养声音与意义的直接连接。' },
                { title: '整句开口', body: '模仿整句的拍数、停顿和语气，不把单词逐个拼起来。' },
                { title: '尽早摆脱罗马字', body: '罗马字只用于理解输入规则；阅读时尽快切换到假名。' },
                { title: 'AI 看意义，也看形式', body: '系统接受等义表达，并指出助词、活用或用词中真正影响自然度的问题。' },
                { title: 'FSRS 安排复习', body: '掌握好的项目逐渐拉长间隔；不稳的内容更快回来。' },
                { title: '汉字按词学习', body: '每个汉字在实际词语中学习读音，避免一次死背全部音读和训读。' },
            ],
            lessonTitle: '每一课的完整循环',
            lessonSteps: [
                ['01', '理解', '看课文、词汇、假名读音和语法说明，先获得完整语境。'],
                ['02', '听与跟读', '反复播放句子，按拍跟读，注意长音、促音和停顿。'],
                ['03', '输出与反馈', '完成翻译、听写和口语任务，获得分层 AI 反馈。'],
                ['04', '间隔复习', 'FSRS 根据结果安排下次出现时间，把时间花在薄弱点上。'],
            ],
            scopeTitle: '基础模块学习顺序',
            scope: [
                ['1', '假名', '掌握 46 个基础音及浊音、拗音、促音和长音符号。'],
                ['2', '发音与节拍', '用“拍”而不是汉语音节理解日语节奏。'],
                ['3', '日语汉字', '理解音读、训读、送假名和按词记忆策略。'],
                ['4', '输入法', '会用罗马字输入假名，并通过候选栏转换汉字。'],
            ],
            noteTitle: '关于手写与音调',
            note: '本课程优先培养阅读、听力、口语和电脑/手机输入。笔顺和手写值得单独练习，但不是进入课文的前置门槛；高低音调会逐步提醒，初期先把元音、拍数、长短音和促音说清楚。',
        },
        kana: {
            eyebrow: 'Writing system · 文字系统',
            title: '假名不是两套发音，而是同一套音的两种写法',
            subtitle: '平假名用于语法成分和常见词，片假名多用于外来语。先建立“字符 → 声音”的直接反应，再学习组合规则。',
            chartTitle: '五十音图（现代常用 46 音）',
            chartNote: '切换文字后点击任意假名听音。表格按元音 a · i · u · e · o 排列；空格表示现代标准日语没有对应基础假名。',
            hiragana: '平假名',
            katakana: '片假名',
            vowels: ['a', 'i', 'u', 'e', 'o'],
            voicedTitle: '浊音与半浊音',
            voicedLabels: ['浊音 G', '浊音 Z', '浊音 D', '浊音 B', '半浊音 P'],
            voicedBody: '右上角的两点「゛」让辅音浊化；小圆圈「゜」把 H 行变成 P 行。ぢ/づ 的常见读音接近 じ/ず，但拼写不能随意替换。',
            contractedTitle: '拗音：一拍读完',
            contractedBody: 'I 段假名（き、し、ち等）加小写 ゃ・ゅ・ょ，合成一拍。きゃ 是 kya，不是 ki-ya 两拍。',
            marksTitle: '四个必须立刻认出的符号',
            marks: [
                ['っ / ッ', '促音', '停住一拍，再发后面的辅音', 'きって · 切手'],
                ['ゃゅょ / ャュョ', '小假名', '和前一个假名合成一拍', 'りょこう · 旅行'],
                ['ー', '片假名长音符', '把前一个元音延长一拍', 'コーヒー'],
                ['を / ん', '特殊基础假名', 'を作助词通常读 o；ん独占一拍', '本を読む · ほん'],
            ],
            planTitle: '七天识读计划',
            plan: [
                '第 1–2 天：平假名 A/K/S/T/N 行，边听边认。',
                '第 3 天：平假名 H/M/Y/R/W 行与 ん，混合抽认。',
                '第 4–5 天：用同样顺序学习片假名，并对比易混字。',
                '第 6 天：浊音、半浊音、拗音、促音和长音。',
                '第 7 天：读真实词语，不再给罗马字提示。',
            ],
            confusionTitle: '高频易混组合',
            confusions: [
                ['ぬ / め', '看右下收笔：ぬ有明显回圈。'],
                ['れ / わ / ね', '先认左侧竖笔，再看右侧是否闭合。'],
                ['シ / ツ', 'シ 的短画更横，ツ 的短画更竖；长画起笔方向也不同。'],
                ['ソ / ン', 'ソ 的短画偏竖，ン 的短画偏横；结合词语反复认。'],
            ],
            quizTitle: '假名识读',
            quizHelp: '选出屏幕上假名的罗马字。罗马字只在这里作核对工具。',
        },
        pronunciation: {
            eyebrow: 'Sound system · 语音系统',
            title: '日语节奏的核心单位是“拍”',
            subtitle: '每个基础假名通常占一拍；长音、促音「っ」和拨音「ん」也各占一拍。先把拍数说准，再追求自然语调。',
            vowelTitle: '五个元音：保持短、纯、稳定',
            vowels: [
                ['あ', 'a', '[a]', '接近“啊”，口腔打开，不滑向其他元音', 'あさ · 朝'],
                ['い', 'i', '[i]', '接近“衣”，嘴角略展开', 'いえ · 家'],
                ['う', 'u', '[ɯ]', '不是汉语圆唇“乌”；嘴唇较放松、较扁', 'うみ · 海'],
                ['え', 'e', '[e̞]', '介于普通话“诶”和“欸”的纯元音', 'えき · 駅'],
                ['お', 'o', '[o̞]', '嘴唇轻圆，保持单一元音', 'おと · 音'],
            ],
            moraTitle: '拍数决定词的骨架',
            moraBody: '不要按汉字个数或罗马字母个数计数。小写ゃゅょ和前项合成一拍；长音、っ、ん则各自占一拍。',
            moraExamples: [
                ['にほん', 'に・ほ・ん', '3 拍'],
                ['きょう', 'きょ・う', '2 拍'],
                ['きって', 'き・っ・て', '3 拍'],
                ['とうきょう', 'と・う・きょ・う', '4 拍'],
            ],
            contrastsTitle: '会改变词义的四组对立',
            contrasts: [
                { title: '长音', left: ['おばさん', '阿姨'], right: ['おばあさん', '奶奶'], note: '多出来的「あ」必须延长一整拍。' },
                { title: '促音', left: ['さか', '坡'], right: ['さっか', '作家'], note: '「っ」不发独立元音，但要留出一拍闭塞。' },
                { title: '拗音', left: ['きやく', '規約'], right: ['きゃく', '客'], note: '大写「や」两拍，小写「ゃ」与前项合成一拍。' },
                { title: '拨音', left: ['たに', '山谷'], right: ['たんい', '单位'], note: '「ん」必须占拍，音色会受后续辅音影响。' },
            ],
            consonantTitle: '中文母语者常见难点',
            consonants: [
                ['ら行', '不是汉语 l，也不是持续颤动的 r；舌尖轻触齿龈一次。'],
                ['ふ', '双唇轻轻接近吹气，不等同于上齿咬下唇的英语 f。'],
                ['し / ち / つ', '分别按 shi / chi / tsu 起步，但最终要通过日语原声校准。'],
                ['清浊音', 'か/が、た/だ等不只看“送不送气”；要听声带是否振动。'],
                ['元音弱化', 'です、好き中的 i/u 可能弱化甚至近乎听不见，但拍位仍在。'],
            ],
            pitchTitle: '高低音调：重要，但不要抢跑',
            pitchBody: '标准日语用音高走势区分词形，不像普通话用固定声调附着每个音节。初学阶段优先保证元音、拍数、长音和促音；随后在整词与整句音频中模仿高低走势，避免用汉语四声逐字套。',
            shadowTitle: '30 秒跟读法',
            shadowSteps: [
                '先不看文字听一遍，只抓拍数和停顿。',
                '看假名，用手指按拍点读；长音、っ、ん都要点到。',
                '跟在原声后约半拍模仿，保持整句连贯。',
                '录下自己，对比“拍数、长短、停顿”，一次只改一个问题。',
            ],
            quizTitle: '数一数有几拍',
            quizHelp: '小写ゃゅょ不单独占拍；长音、っ、ん各占一拍。',
        },
        kanji: {
            eyebrow: 'Kanji · 日语汉字',
            contextHeaders: ['字', '词语', '读音', '含义'],
            componentHeaders: ['部件', '线索', '例字', '常见关联'],
            title: '不要问“这个汉字怎么读”，要问“这个词怎么读”',
            subtitle: '同一个汉字会因词语而有不同读音。最稳妥的单位是：完整词语、假名读音、含义和一个真实例句。',
            systemTitle: '日语汉字的三条核心规律',
            system: [
                { glyph: '日', title: '音读', body: '历史上从汉语传入的读法，常见于复合词。', examples: '日本（にほん）・日曜日（にちようび）' },
                { glyph: '日', title: '训读', body: '把日语固有词的读音配到汉字上，常见于单字词或带送假名的词。', examples: '日（ひ）・日の出（ひので）' },
                { glyph: '食べる', title: '送假名', body: '汉字后的假名提示词尾、活用和读法边界。它是词的一部分，不能省略。', examples: '食べる・食べます・食べない' },
            ],
            contextTitle: '同一个字，放进词里才确定读音',
            contextRows: [
                ['人', '人', 'ひと', '人'],
                ['人', '日本人', 'にほんじん', '日本人'],
                ['人', '三人', 'さんにん', '三个人'],
                ['生', '学生', 'がくせい', '学生'],
                ['生', '生まれる', 'うまれる', '出生'],
                ['生', '生ビール', 'なまビール', '生啤'],
            ],
            componentsTitle: '部件帮助猜意义和整理记忆',
            componentsBody: '部首和部件可以提示意义类别或结构，但不能保证精确读音。把它们当作“索引”和记忆线索，不当作万能公式。',
            components: [
                ['亻', '人', '休・体・住', '常与人或人的行为有关'],
                ['氵', '水', '海・酒・洗', '常与水、液体或清洗有关'],
                ['言', '语言', '話・語・読', '常与说话、语言或阅读有关'],
                ['木', '树木', '林・校・本', '常见于树木、材料或相关构件'],
                ['日', '太阳/时间', '明・時・曜', '常与光、日期或时间有关'],
            ],
            chineseTitle: '中文母语者：优势很大，也要防“望字生义”',
            chinesePairs: [
                ['手紙', 'てがみ', '信件', '不是“手纸”'],
                ['勉強', 'べんきょう', '学习', '不是“勉强”'],
                ['丈夫', 'じょうぶ', '结实、健康', '日语“丈夫”不表示丈夫'],
                ['娘', 'むすめ', '女儿/年轻女子', '含义范围与现代汉语不同'],
                ['汽車', 'きしゃ', '火车（多指蒸汽机车）', '现代常用 電車 表示电车'],
            ],
            methodTitle: '一个词的正确记法',
            methodSteps: [
                ['1', '看完整词', '日本語，不拆成三个孤立汉字。'],
                ['2', '绑定读音', 'にほんご，整词朗读并按拍切分。'],
                ['3', '放进句子', '日本語を勉強します。'],
                ['4', '复习时回忆', '看到词先说读音与意思，再检查答案。'],
            ],
            cautionTitle: '不建议这样背',
            caution: '不要在第一次遇到「生」时试图背完所有音读、训读和特殊读法。先掌握当前词中的读音；遇到新词时再把新读法挂到已有网络上。',
            quizTitle: '按词选择读音',
            quizHelp: '不要只看单个汉字，用完整词语判断。',
        },
        typing: {
            eyebrow: 'Japanese IME · 日语输入法',
            title: '输入日语：先打读音，再选择文字',
            subtitle: '普通键盘不需要日文键帽。启用日语输入法后，用罗马字生成假名，再用空格从候选中选择汉字，回车确认。',
            flowTitle: '核心流程只有三步',
            flow: [
                ['1', '输入读音', 'nihongo', 'にほんご'],
                ['2', '空格转换', 'Space', '日本語'],
                ['3', '回车确认', 'Enter', '日本語'],
            ],
            setupTitle: '在设备上启用日语键盘',
            setupNote: '系统菜单名称会随版本略有差异；找不到时在设置中搜索“语言”“键盘”或“Japanese”。',
            platforms: [
                { name: 'Windows 11', icon: '⊞', steps: ['设置 → 时间和语言 → 语言和区域。', '添加语言并选择“日本語”；确认安装 Microsoft IME。', '用 Win + Space 切换语言，并确认输入模式为“あ”（平假名）。'], url: 'https://support.microsoft.com/windows/hardware/input-devices/microsoft-japanese-ime' },
                { name: 'macOS', icon: '⌘', steps: ['系统设置 → 键盘 → 文本输入 → 编辑。', '添加“日语”，选择“日语－罗马字”。', '用菜单栏输入菜单或系统设置的切换键切换到平假名。'], url: 'https://support.apple.com/guide/japanese-input-method/jpim10267/mac' },
                { name: 'iPhone / iPad', icon: '◉', steps: ['设置 → 通用 → 键盘 → 键盘。', '添加新键盘 → 日语；可选“罗马字”或“假名”。', '输入时长按地球键切换键盘。'], url: 'https://support.apple.com/guide/iphone/iph73b71eb/ios' },
                { name: 'Android / Gboard', icon: '◆', steps: ['打开 Gboard 设置 → 语言。', '添加键盘并选择日语及偏好的布局。', '用地球键或长按空格切换语言。'], url: 'https://support.google.com/gboard/answer/2842292' },
            ],
            rulesTitle: '罗马字输入的关键规则',
            rules: [
                ['基本音', 'ka → か · shi → し · tsu → つ', '多数假名按常见罗马字直接输入。'],
                ['拗音', 'kyo → きょ · sha → しゃ', '小写ゃゅょ不要拆成 kiyo / shiya。'],
                ['促音', 'kitte → きって', '把后一个辅音写两次；っ会自动出现。'],
                ['拨音 ん', 'hon → ほん · annai → あんない', '在元音或 y 前通常用 nn 或 n\'，避免被合成下一拍。'],
                ['片假名长音', 'ko-hi- → コーヒー', '连字符输入「ー」；实际键位和输入法设置有关。'],
                ['小假名', 'xa → ぁ · xtsu/ltsu → っ', 'x 或 l 前缀可直接输入小写假名。'],
                ['助词', 'ha → は · he → へ · wo → を', '句中虽常读 wa/e/o，拼写仍按 は/へ/を 输入。'],
            ],
            conversionTitle: '候选转换要按“词组”进行',
            conversionBody: '输入较完整的短语，IME 更容易根据上下文选对汉字。例如输入「きょうはにほんごをべんきょうします」后再转换，通常比逐字转换准确。候选不对时缩短分词边界或重新转换，不要盲按回车。',
            shortcutTitle: '先记住这四个键',
            shortcuts: [
                ['Space', '转换 / 切换候选'],
                ['Enter', '确认当前文字'],
                ['Esc', '取消当前转换'],
                ['Win + Space / 输入源切换键', '切换系统输入语言'],
            ],
            practiceTitle: '真实输入练习',
            practiceHelp: '先把系统输入法切到日语平假名模式。输入目标文字后点“检查”；答案只在浏览器内比较，不会保存。',
            inputPlaceholder: '在这里使用日语输入法输入…',
            check: '检查',
            matched: '输入正确。继续下一条。',
            notMatched: '还不一致。检查输入模式、长音、促音、助词和汉字候选。',
            reset: '清空重练',
            privacy: '练习内容只保存在当前页面状态中。',
            habitTitle: '三个能明显提速的习惯',
            habits: [
                '按词组输入并观察候选，不要每输入一个假名就确认。',
                '确认前再看一眼助词、长音和汉字；IME 会学习你选过的候选。',
                '阅读时不依赖罗马字，输入时才把罗马字当作键盘编码。',
            ],
        },
    },
    en: {
        common: {
            courseBadge: 'Chilan · Japanese foundations',
            back: 'Back',
            step: 'Step',
            listen: 'Play audio', listening: 'Playing', audioError: 'Audio is unavailable right now. Please try again later.',
            readingOnly: 'Understand the pattern first; you do not need to memorize everything at once',
            quiz: 'Quick check', correct: 'Correct', incorrect: 'Try again', next: 'Next', restart: 'Restart', score: 'Score {{score}} / {{total}}',
        },
        intro: {
            eyebrow: 'Before lesson one', title: 'See how Japanese works before memorizing sentences',
            slidesAriaLabel: 'Japanese course introduction slides',
            subtitle: 'Japanese combines three scripts, mora-timed sound, inflection, and context. This guide shows what each foundation module covers and what “ready” looks like.',
            scriptTitle: 'Three scripts, three jobs',
            scripts: [
                { glyph: 'あ', title: 'Hiragana', tag: 'Grammar and native words', body: 'Particles, endings, and many common words use hiragana. Build direct recognition without romaji.', example: 'わたしは学生です。' },
                { glyph: 'ア', title: 'Katakana', tag: 'Loanwords and emphasis', body: 'Loanwords, names, and sound-symbolic words often use katakana. It represents the same core sounds as hiragana.', example: 'コーヒーを飲みます。' },
                { glyph: '漢', title: 'Kanji', tag: 'Meaning and word stems', body: 'Kanji compress meaning, but readings change by word. Learn a whole word with its reading and context.', example: '日本語を勉強します。' },
            ],
            principlesTitle: 'How to use this course',
            principles: [
                { title: 'Listen before reading', body: 'Hear the full expression first, then use kana and translation to verify it.' },
                { title: 'Speak whole phrases', body: 'Copy mora count, pauses, and intonation instead of assembling isolated words.' },
                { title: 'Leave romaji early', body: 'Use romaji to learn keyboard rules, not as a permanent reading aid.' },
                { title: 'AI checks meaning and form', body: 'Equivalent answers are accepted while particles, inflection, and natural wording still receive precise feedback.' },
                { title: 'FSRS schedules reviews', body: 'Stable items wait longer; uncertain items return sooner.' },
                { title: 'Learn kanji in words', body: 'Attach each reading to a real word rather than memorizing every reading in isolation.' },
            ],
            lessonTitle: 'The complete lesson loop',
            lessonSteps: [['01', 'Understand', 'Study the text, vocabulary, readings, and grammar in context.'], ['02', 'Listen and shadow', 'Replay sentences and copy mora timing, long vowels, and pauses.'], ['03', 'Produce and get feedback', 'Complete translation, dictation, and speaking tasks with layered AI feedback.'], ['04', 'Review at the right time', 'FSRS brings each item back when it is most useful.']],
            scopeTitle: 'Recommended foundation order',
            scope: [['1', 'Kana', 'Recognize the 46 basic sounds plus voiced, contracted, geminate, and long forms.'], ['2', 'Pronunciation', 'Hear Japanese in morae rather than English-style syllables.'], ['3', 'Kanji', 'Understand on/kun readings, okurigana, and word-based study.'], ['4', 'Typing', 'Generate kana with romaji and convert it to kanji with an IME.']],
            noteTitle: 'Handwriting and pitch accent',
            note: 'The course prioritizes reading, listening, speaking, and digital input. Handwriting deserves separate practice but is not a prerequisite for lessons. Pitch accent is introduced progressively; first make vowels, mora count, vowel length, and geminates clear.',
        },
        kana: {
            eyebrow: 'Writing system', title: 'Kana are two spellings for the same sound system',
            subtitle: 'Hiragana carries grammar and many common words; katakana often marks loanwords. Build a direct character-to-sound response before studying combinations.',
            chartTitle: 'The modern 46-kana chart', chartNote: 'Switch scripts and select any kana to hear it. Columns follow a · i · u · e · o; blanks have no modern basic kana.', hiragana: 'Hiragana', katakana: 'Katakana', vowels: ['a', 'i', 'u', 'e', 'o'],
            voicedTitle: 'Voiced and semi-voiced kana', voicedBody: 'Dakuten 「゛」voices a consonant; handakuten 「゜」turns the H row into P. ぢ/づ usually sound like じ/ず, but their spellings are not interchangeable.',
            voicedLabels: ['Voiced G', 'Voiced Z', 'Voiced D', 'Voiced B', 'Semi-voiced P'],
            contractedTitle: 'Contracted sounds take one mora', contractedBody: 'An i-column kana plus small ゃ・ゅ・ょ forms one mora. きゃ is kya, not ki-ya.',
            marksTitle: 'Four patterns to recognize immediately',
            marks: [['っ / ッ', 'Geminate marker', 'Hold one mora before the next consonant', 'きって · stamp'], ['ゃゅょ / ャュョ', 'Small kana', 'Combines with the previous kana into one mora', 'りょこう · travel'], ['ー', 'Katakana long-vowel mark', 'Extends the preceding vowel by one mora', 'コーヒー'], ['を / ん', 'Special basics', 'を as a particle is usually o; ん occupies one mora', '本を読む · ほん']],
            planTitle: 'A seven-day recognition plan', plan: ['Days 1–2: Hiragana A/K/S/T/N rows with audio.', 'Day 3: Hiragana H/M/Y/R/W rows and ん; mix the deck.', 'Days 4–5: Katakana in the same order; contrast similar forms.', 'Day 6: Voiced, semi-voiced, contracted, geminate, and long forms.', 'Day 7: Read real words without romaji.'],
            confusionTitle: 'Common look-alikes', confusions: [['ぬ / め', 'Check the lower-right finish: ぬ has a clear loop.'], ['れ / わ / ね', 'Find the left stroke, then check whether the right side closes.'], ['シ / ツ', 'シ has more horizontal short strokes; ツ has more vertical ones.'], ['ソ / ン', 'ソ starts more vertically; ン starts more horizontally. Learn them in words.']],
            quizTitle: 'Kana recognition', quizHelp: 'Choose the romaji for the kana. Romaji is only a checking tool here.',
        },
        pronunciation: {
            eyebrow: 'Sound system', title: 'The core unit of Japanese rhythm is the mora',
            subtitle: 'A basic kana usually takes one mora; long vowels, small っ, and ん also take one each. Make timing clear before chasing native-like pitch.',
            vowelTitle: 'Five short, steady vowels',
            vowels: [['あ', 'a', '[a]', 'Open and steady, without gliding', 'あさ · morning'], ['い', 'i', '[i]', 'Front vowel with lightly spread lips', 'いえ · house'], ['う', 'u', '[ɯ]', 'Less rounded than English “oo”', 'うみ · sea'], ['え', 'e', '[e̞]', 'A steady mid-front vowel', 'えき · station'], ['お', 'o', '[o̞]', 'Lightly rounded and steady', 'おと · sound']],
            moraTitle: 'Mora count is the word’s frame', moraBody: 'Do not count kanji or roman letters. Small ゃゅょ joins the preceding kana; a long vowel, っ, and ん each add a mora.',
            moraExamples: [['にほん', 'に・ほ・ん', '3 morae'], ['きょう', 'きょ・う', '2 morae'], ['きって', 'き・っ・て', '3 morae'], ['とうきょう', 'と・う・きょ・う', '4 morae']],
            contrastsTitle: 'Four meaning-changing contrasts',
            contrasts: [{ title: 'Vowel length', left: ['おばさん', 'aunt'], right: ['おばあさん', 'grandmother'], note: 'The extra あ lasts a full mora.' }, { title: 'Gemination', left: ['さか', 'slope'], right: ['さっか', 'author'], note: 'Small っ is a silent closure that still takes one mora.' }, { title: 'Contracted sound', left: ['きやく', 'regulations'], right: ['きゃく', 'guest'], note: 'Large や is separate; small ゃ merges into one mora.' }, { title: 'Moraic nasal', left: ['たに', 'valley'], right: ['たんい', 'unit'], note: 'ん occupies a mora and changes shape before different consonants.' }],
            consonantTitle: 'Frequent learner challenges', consonants: [['R row', 'A single light tongue tap, not English r or l.'], ['ふ', 'Bring both lips close and release air; do not bite the lower lip.'], ['し / ち / つ', 'Start with shi / chi / tsu, then calibrate against native audio.'], ['Voicing', 'Pairs such as か/が differ in vocal-fold vibration, not only aspiration.'], ['Vowel devoicing', 'High vowels in です or 好き may weaken, but the timing slot remains.']],
            pitchTitle: 'Pitch accent matters, but sequence matters more', pitchBody: 'Standard Japanese distinguishes words through pitch patterns rather than a fixed tone on every syllable. First secure vowels, morae, length, and geminates; then imitate whole-word and sentence pitch without imposing tones from another language.',
            shadowTitle: 'A 30-second shadowing loop', shadowSteps: ['Listen once without text and notice timing and pauses.', 'Read kana and tap every mora, including length, っ, and ん.', 'Shadow about half a beat behind the audio.', 'Record yourself and fix one issue at a time: count, length, or pause.'],
            quizTitle: 'Count the morae', quizHelp: 'Small ゃゅょ merges; long vowels, っ, and ん each count.',
        },
        kanji: {
            eyebrow: 'Kanji', title: 'Ask how the word is read, not how the kanji is read',
            contextHeaders: ['Kanji', 'Word', 'Reading', 'Meaning'],
            componentHeaders: ['Part', 'Cue', 'Examples', 'Common link'],
            subtitle: 'One character can have different readings in different words. The reliable learning unit is a whole word, its kana reading, meaning, and a real example.',
            systemTitle: 'Three core ideas', system: [{ glyph: '日', title: 'On reading', body: 'Historically borrowed readings, frequent in compounds.', examples: '日本（にほん）・日曜日（にちようび）' }, { glyph: '日', title: 'Kun reading', body: 'Native Japanese words mapped to kanji, common in standalone words and words with okurigana.', examples: '日（ひ）・日の出（ひので）' }, { glyph: '食べる', title: 'Okurigana', body: 'Kana after kanji shows endings, inflection, and reading boundaries. It is part of the word.', examples: '食べる・食べます・食べない' }],
            contextTitle: 'Context determines the reading', contextRows: [['人', '人', 'ひと', 'person'], ['人', '日本人', 'にほんじん', 'Japanese person'], ['人', '三人', 'さんにん', 'three people'], ['生', '学生', 'がくせい', 'student'], ['生', '生まれる', 'うまれる', 'to be born'], ['生', '生ビール', 'なまビール', 'draft beer']],
            componentsTitle: 'Components organize meaning and memory', componentsBody: 'Radicals and components can hint at a semantic area or structure, but rarely guarantee a reading. Use them as indexes and memory cues, not formulas.',
            components: [['亻', 'person', '休・体・住', 'people and human actions'], ['氵', 'water', '海・酒・洗', 'water, liquids, washing'], ['言', 'speech', '話・語・読', 'speech, language, reading'], ['木', 'tree', '林・校・本', 'trees, materials, related forms'], ['日', 'sun/time', '明・時・曜', 'light, dates, time']],
            chineseTitle: 'Kanji words that can mislead', chinesePairs: [['手紙', 'てがみ', 'letter', 'Learn the whole word instead of guessing character by character.'], ['勉強', 'べんきょう', 'study', 'The combined word has its own everyday meaning.'], ['丈夫', 'じょうぶ', 'sturdy / healthy', 'The real meaning may differ from what the characters suggest.'], ['娘', 'むすめ', 'daughter / young woman', 'Context determines the word’s exact range.'], ['汽車', 'きしゃ', 'train / steam locomotive', '電車 is common for electric trains']],
            methodTitle: 'How to learn one word', methodSteps: [['1', 'See the whole word', '日本語, not three isolated characters.'], ['2', 'Attach the reading', 'にほんご, spoken and segmented by mora.'], ['3', 'Put it in a sentence', '日本語を勉強します。'], ['4', 'Recall before checking', 'Say reading and meaning before revealing the answer.']],
            cautionTitle: 'Avoid the reading dump', caution: 'Do not memorize every reading of 生 the first time you see it. Learn the reading in the current word; add another branch when a new word appears.',
            quizTitle: 'Choose the word reading', quizHelp: 'Use the complete word, not an isolated character.',
        },
        typing: {
            eyebrow: 'Japanese IME', title: 'Type the reading, then choose the writing',
            subtitle: 'No Japanese keycaps are required. A Japanese IME turns romaji into kana; Space selects kanji candidates and Enter confirms.',
            flowTitle: 'The three-step flow', flow: [['1', 'Type the reading', 'nihongo', 'にほんご'], ['2', 'Convert', 'Space', '日本語'], ['3', 'Confirm', 'Enter', '日本語']],
            setupTitle: 'Enable a Japanese keyboard', setupNote: 'Menu labels vary slightly by OS version. Search Settings for “language,” “keyboard,” or “Japanese” if needed.',
            platforms: [{ name: 'Windows 11', icon: '⊞', steps: ['Settings → Time & language → Language & region.', 'Add Japanese and make sure Microsoft IME is installed.', 'Use Win + Space to switch, then choose Hiragana “あ” mode.'], url: 'https://support.microsoft.com/windows/hardware/input-devices/microsoft-japanese-ime' }, { name: 'macOS', icon: '⌘', steps: ['System Settings → Keyboard → Text Input → Edit.', 'Add Japanese and choose Japanese – Romaji.', 'Switch from the Input menu or your configured input-source shortcut.'], url: 'https://support.apple.com/guide/japanese-input-method/jpim10267/mac' }, { name: 'iPhone / iPad', icon: '◉', steps: ['Settings → General → Keyboard → Keyboards.', 'Add New Keyboard → Japanese; choose Romaji or Kana.', 'Hold the globe key while typing to switch keyboards.'], url: 'https://support.apple.com/guide/iphone/iph73b71eb/ios' }, { name: 'Android / Gboard', icon: '◆', steps: ['Open Gboard Settings → Languages.', 'Add Japanese and choose a layout.', 'Use the globe key or long-press Space to switch.'], url: 'https://support.google.com/gboard/answer/2842292' }],
            rulesTitle: 'Essential romaji-input rules', rules: [['Basic kana', 'ka → か · shi → し · tsu → つ', 'Most kana use familiar romanization.'], ['Contracted sounds', 'kyo → きょ · sha → しゃ', 'Do not split small ゃゅょ into kiyo / shiya.'], ['Small っ', 'kitte → きって', 'Double the following consonant.'], ['ん', 'hon → ほん · annai → あんない', 'Before a vowel or y, use nn or n\' to prevent merging.'], ['Katakana length', 'ko-hi- → コーヒー', 'A hyphen can enter ー; exact keys depend on the IME.'], ['Small kana', 'xa → ぁ · xtsu/ltsu → っ', 'Prefix x or l for a small kana.'], ['Particles', 'ha → は · he → へ · wo → を', 'They may sound wa/e/o but keep their spelling.']],
            conversionTitle: 'Convert phrase-sized chunks', conversionBody: 'An IME chooses better kanji with context. Type a useful phrase before conversion; if segmentation is wrong, adjust the conversion boundary instead of confirming blindly.',
            shortcutTitle: 'Four controls to remember', shortcuts: [['Space', 'Convert / cycle candidates'], ['Enter', 'Confirm'], ['Esc', 'Cancel the current conversion'], ['Win + Space / input-source shortcut', 'Switch system input language']],
            practiceTitle: 'Real IME practice', practiceHelp: 'Switch your system IME to Japanese Hiragana mode. Enter the target and select Check. Text is only compared in this page state.', inputPlaceholder: 'Type here with a Japanese IME…', check: 'Check', matched: 'Correct. Move to the next line.', notMatched: 'Not quite. Check input mode, vowel length, small っ, particles, and the kanji candidate.', reset: 'Clear and retry', privacy: 'Practice text stays only in the current page state.',
            habitTitle: 'Three habits that speed you up', habits: ['Type phrase-sized chunks and inspect candidates.', 'Before confirming, recheck particles, vowel length, and kanji.', 'Read without romaji; use romaji only as a keyboard encoding.'],
        },
    },
    ...JAPANESE_FOUNDATION_TRANSLATIONS,
};

export function getFoundationCopy(supportLanguageCode) {
    return FOUNDATION_COPY[normalizeJapaneseFoundationLanguage(supportLanguageCode)] || FOUNDATION_COPY.en;
}
